# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-'SCRIPT'
#!/bin/bash
apt-get update
apt-get install -y python3 python3-pip python3-dev git

curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs

pip3 install pymongo flask flask-cors

wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
apt-get update
apt-get install -y mongodb-org

systemctl start mongod


SCRIPT

Vagrant.configure(2) do |config|
	config.vm.box = "debian/buster64"			
	config.vm.box_check_update = false
	
	config.vm.define 'admin' do |machine|
		machine.vm.hostname = "admin"	
		machine.vm.network 'public_network', ip: '192.168.1.118'		
		machine.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = 4096
			vb.cpus = 4
		end
	end
	
	config.vm.synced_folder '../src', '/home/src'
	 config.vm.provision "shell", inline: $script
end