version: '3.9'

services: 

    mongo:
        image: mongo
        restart: always
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb:/data/db

    back:
        depends_on: 
            - mongo
        build: 
            dockerfile: Dockerfile-flask
            context: .
        ports: 
            - 5000:5000
        restart: always
        
    front:
        depends_on: 
            - back
        build: 
            dockerfile: Dockerfile-node
            context: .
        ports: 
            - 4200:4200
        restart: always 
        command:  ng serve --host 0.0.0.0 --disable-host-check --prod
            
volumes:
    mongodb:
