FROM python:3.7-alpine

WORKDIR /app

# Update et recupere git
RUN apk update \
 && apk add git
 
# Optimisation
RUN apk add --no-cache gcc musl-dev linux-headers

# Copie du depot
RUN git clone https://github.com/Groupe2filRouge/AppFilRougeAdmin.git

# Copie des fichiers necessaires
RUN cp AppFilRougeAdmin/src/main/app.py .
RUN cp -r AppFilRougeAdmin/src/main/service .
RUN cp AppFilRougeAdmin/src/requirements.txt .

# Suppression des dossiers inutiles
RUN rm -r AppFilRougeAdmin/

# Installation des dependances
RUN pip install -r requirements.txt

# Copie du docker intermediaire vers le courant
COPY . .

# Suppression des fichiers inutiles
RUN rm requirements.txt

# Regle de "pare-feu" => on expose le port 5000 => - ports : - 5000:5000 dans le docker-compose
EXPOSE 5000

CMD ["python3", "app.py"]
