FROM node:14.17-alpine

WORKDIR /app

# Update et recupere git
RUN apk update \
 && apk add git

 # Optimisation
RUN apk add --no-cache gcc musl-dev linux-headers

# Copie du depot
RUN git clone https://github.com/Groupe2filRouge/AppFilRougeAdmin.git

# Copie du fichier necessaires
RUN cp -r AppFilRougeAdmin/src/main/angular-part .

# Suppression des dossiers inutiles
RUN rm -r AppFilRougeAdmin/

# Le repertoire de travail devient l'application
WORKDIR /app/angular-part

# On install l'application
RUN npm i

# On installe le cli angular
RUN npm i -g @angular/cli

# On build l'application en mode production
RUN ng build --configuration production

# Commande au demarrage
CMD ["ng" , "serve", "--host", "0.0.0.0", "--disable-host-check", "--configuration", "production"]

# Ex: docker build --no-cache -f /home/src/Dockerfile-node -t apalpant/node .
# Ex: docker run --rm -p 4200:4200 -e BASE_URL=192.168.1.118 --name node apalpant/node
