FROM node:14.17-alpine

WORKDIR /app

# Update et recupere git
RUN apk update \
 && apk add git

 # Optimisation
RUN apk add --no-cache gcc musl-dev linux-headers

# Copie du depot
RUN git clone https://github.com/Groupe2filRouge/AppFilRougeAdmin.git

# Copie du fichier necessaires
RUN cp -r AppFilRougeAdmin/src/main/angular-part .

# Suppression des dossiers inutiles
RUN rm -r AppFilRougeAdmin/

WORKDIR /app/angular-part

RUN npm i
RUN ls

RUN npm run build --prod

# Copie du docker intermediaire vers le courant
COPY . .

EXPOSE 4200

CMD ["npm start"]