version: '3.9'

services: 

    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    back:
        depends_on: 
            - db
        build: 
            dockerfile: Dockerfile-flask
            context: .
        ports: 
            - 5000:5000
        restart: always
        
    front:
        depends_on: 
            - back
        build: 
            dockerfile: Dockerfile-node
            context: .
        ports: 
            - 4200:4200
        restart: always 
        environment:
            BASE_URL: 192.168.1.118
            